# Generated by Django 2.0 on 2019-03-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=30)),
                ('discount_percentage', models.FloatField()),
                ('max_discount_price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('mode_of_payment', models.IntegerField()),
                ('max_no_of_orders', models.IntegerField()),
                ('min_order_price', models.IntegerField()),
                ('min_time_difference', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('min_order_price', models.IntegerField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.Restaurant')),
            ],
        ),
    ]
