# Generated by Django 2.0 on 2019-03-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_app', '0001_initial'),
        ('addons_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('original_price', models.FloatField()),
                ('discounted_price', models.FloatField(null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('is_veg', models.BooleanField()),
                ('rating', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Category')),
                ('offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='addons_app.RestaurantOffer')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.Restaurant')),
            ],
        ),
    ]
