# Generated by Django 2.0 on 2019-03-30 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_app', '0001_initial'),
        ('restaurant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Cost', models.FloatField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('billResId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.Restaurant')),
                ('billuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCreatedTime', models.DateTimeField(null=True)),
                ('orderPaidTime', models.DateTimeField(null=True)),
                ('orderRestaurantConfirmedTime', models.DateTimeField(null=True)),
                ('ordercompleted', models.DateTimeField(null=True)),
                ('Status', models.PositiveSmallIntegerField(choices=[(1, 'intiated'), (2, 'processing'), (3, 'completed'), (4, 'rejected')], default=1)),
                ('Payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Online Payment'), (2, 'Direct Payment')], null=True)),
                ('paymentCompleted', models.BooleanField(default=False)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('itemCost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('restaurantConfirmation', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cartItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Menu')),
                ('cartUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalcost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='permanentcart',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartuser', to='temperorycart.TotalCost'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_cost', to='temperorycart.TotalCost'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billorderno', to='temperorycart.TotalCost'),
        ),
    ]
