# Generated by Django 2.0 on 2019-04-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization_app', '0001_initial'),
        ('menu_app', '0001_initial'),
        ('temperorycart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMenuCustommization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization_app.Customization')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Menu')),
            ],
        ),
    ]
