# Generated by Django 2.0 on 2019-04-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
        ('customization_app', '0001_initial'),
        ('temperorycart', '0002_cartmenucustommization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartMenuCustommization',
            new_name='CartMenuCustomization',
        ),
    ]
