# Generated by Django 2.0 on 2019-04-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temperorycart', '0003_auto_20190402_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmenucustomization',
            name='customUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
