# Generated by Django 2.0 on 2019-04-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization_app', '0001_initial'),
        ('temperorycart', '0007_remove_cartmenucustomization_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOnQuantiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartMenuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custommenu', to='temperorycart.CartMenuCustomization')),
                ('custoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartmmenucustomisation', to='customization_app.Customization')),
            ],
        ),
    ]
