# Generated by Django 2.0 on 2019-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization_app', '0001_initial'),
        ('temperorycart', '0008_customizationonquantiy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomizationOnQuantiy',
            new_name='CustomizationOnQuantity',
        ),
    ]
