# Generated by Django 2.0 on 2019-04-03 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customization_app', '0001_initial'),
        ('temperorycart', '0009_auto_20190403_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationonquantity',
            name='custoId',
        ),
        migrations.AddField(
            model_name='customizationonquantity',
            name='customId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cartmmenucustomisation', to='customization_app.Customization'),
            preserve_default=False,
        ),
    ]
