# Generated by Django 2.0 on 2019-03-30 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_activated', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('is_veg', models.BooleanField()),
                ('approved_admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_restaurants', to=settings.AUTH_USER_MODEL)),
                ('res_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
